# Generated by Django 2.1 on 2018-08-31 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('-year', 'title')},
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='run_time',
            new_name='runtime',
        ),
    ]
